## CHECK THESE FORCES ALL MATCH UP ##

police_forces = {
    "E23000001": "Metropolitan Police",
    "E23000002": "Cumbria",
    "E23000003": "Lancashire",
    "E23000004": "Merseyside",
    "E23000005": "Greater Manchester",
    "E23000006": "Cheshire",
    "E23000007": "Northumbria",
    "E23000008": "Durham",
    "E23000009": "North Yorkshire",
    "E23000010": "West Yorkshire",
    "E23000011": "South Yorkshire",
    "E23000012": "Humberside",
    "E23000013": "Cleveland",
    "E23000014": "West Midlands",
    "E23000015": "Staffordshire",
    "E23000016": "West Mercia",
    "E23000017": "Warwickshire",
    "E23000018": "Derbyshire",
    "E23000019": "Nottinghamshire",
    "E23000020": "Lincolnshire",
    "E23000021": "Leicestershire",
    "E23000022": "Northamptonshire",
    "E23000023": "Cambridgeshire",
    "E23000024": "Norfolk",
    "E23000025": "Suffolk",
    "E23000026": "Bedfordshire",
    "E23000027": "Hertfordshire",
    "E23000028": "Essex",
    "E23000029": "Thames Valley",
    "E23000030": "Hampshire",
    "E23000031": "Surrey",
    "E23000032": "Kent",
    "E23000033": "Sussex",
    "E23000034": "London, City of",
    "E23000035": "Devon and Cornwall",
    "E23000036": "Avon and Somerset",
    "E23000037": "Gloucestershire",
    "E23000038": "Wiltshire",
    "E23000039": "Dorset",
    "L99999999": "Pseudo Channel Islands",
    "M99999999": "Pseudo Isle of Man",
    "N99999999": "Northern Ireland",
    "S23000009": "Scotland",
    "W15000001": "North Wales",
    "W15000002": "Gwent",
    "W15000003": "South Wales",
    "W15000004": "Dyfed-Powys"
}

offence_types = [
    "Arson endangering life",
    "Arson not endangering life",
    "Criminal damage to a building other than a dwelling",
    "Criminal damage to a dwelling",
    "Criminal damage to a vehicle",
    "Other criminal damage",
    "Racially or religiously aggravated criminal damage",
    "Other drug offences",
    "Possession of controlled drugs (Cannabis)",
    "Possession of controlled drugs (excl. Cannabis)",
    "Trafficking in controlled drugs",
    "Absconding from lawful custody",
    "Aiding suicide",
    "Bail offences",
    "Bigamy",
    "Concealing an infant death close to birth",
    "Dangerous driving",
    "Disclosure, obstruction, false or misleading statements etc",
    "Exploitation of prostitution",
    "Forgery or use of false drug prescription",
    "Fraud, forgery etc associated with vehicle or driver records",
    "Going equipped for stealing, etc",
    "Handling stolen goods",
    "Making, supplying or possessing articles for use in fraud",
    "Obscene publications etc",
    "Offender Management Act offences",
    "Other forgery",
    "Other notifiable offences",
    "Perjury",
    "Perverting the course of justice",
    "Possession of false documents",
    "Profiting from or concealing knowledge of the proceeds of crime",
    "Soliciting for the purposes of prostitution",
    "Threat or possession with intent to commit criminal damage",
    "Wildlife",
    "Other firearms, knives and offensive weapon offences",
    "Possession of article with blade or point",
    "Possession of firearms offences",
    "Possession of firearms with intent",
    "Possession of other weapons",
    "Other offences against the State or public order",
    "Public fear, alarm or distress",
    "Racially or religiously aggravated public fear, alarm or distress",
    "Violent disorder",
    "Robbery of business property",
    "Robbery of personal property",
    "Abuse of children through sexual exploitation",
    "Abuse of position of trust of a sexual nature",
    "Causing sexual activity without consent",
    "Exposure and voyeurism",
    "Incest or familial sexual offences",
    "Other miscellaneous sexual offences",
    "Sexual activity etc with a person with a mental disorder",
    "Sexual activity involving a child under 13",
    "Sexual activity involving child under 16",
    "Sexual assault on a female aged 13 and over",
    "Sexual assault on a female child under 13",
    "Sexual assault on a male aged 13 and over",
    "Sexual assault on a male child under 13",
    "Sexual grooming",
    "Trafficking for sexual exploitation",
    "Unnatural sexual offences",
    "Rape of a Female - Multiple Undefined Offenders",
    "Rape of a female aged 16 and over",
    "Rape of a female child under 13",
    "Rape of a female child under 16",
    "Rape of a Male - Multiple Undefined Offenders",
    "Rape of a male aged 16 and over",
    "Rape of a male child under 13",
    "Rape of a male child under 16",
    "Theft or unauthorised taking of a pedal cycle",
    "Aggravated Burglary Business and Community",
    "Attempted Burglary Business and Community",
    "Burglary Business and Community",
    "Blackmail",
    "Dishonest use of electricity",
    "Making off without payment",
    "Other theft",
    "Theft by an employee",
    "Theft from automatic machine or meter",
    "Theft in a dwelling other than from an automatic machine or meter",
    "Theft of mail",
    "Aggravated burglary - residential (home)",
    "Aggravated burglary - residential (unconnected building)",
    "Aggravated Burglary Residential",
    "Attempted Burglary Residential",
    "Attempted distraction burglary - residential (home)",
    "Attempted distraction burglary - residential (unconnected building)",
    "Attempted Distraction Burglary Residential",
    "Attempted residential burglary of a home",
    "Attempted residential burglary of unconnected building",
    "Burglary Residential",
    "Distraction burglary - residential (home)",
    "Distraction burglary - residential (unconnected building)",
    "Distraction Burglary Residential",
    "Residential burglary of a home",
    "Residential burglary of unconnected building",
    "Shoplifting",
    "Theft from the person",
    "Aggravated vehicle taking",
    "Interfering with a motor vehicle",
    "Theft from vehicle",
    "Theft or unauthorised taking of motor vehicle",
    "Causing death by aggravated vehicle taking",
    "Causing death by careless driving under influence of drink or drugs",
    "Causing death by driving: unlicensed or disqualified or uninsured drivers",
    "Causing death or serious injury by careless or inconsiderate driving",
    "Causing death or serious injury by dangerous driving",
    "Corporate manslaughter",
    "Infanticide",
    "Manslaughter",
    "Murder",
    "Controlling and coercive behaviour",
    "Harassment",
    "Malicious Communications",
    "Racially or religiously aggravated harassment",
    "Stalking",
    "Assault with injury",
    "Assault with injury on a constable",
    "Assault with intent to cause serious harm",
    "Assaults on emergency workers (other than constables)",
    "Attempted murder",
    "Causing or allowing death of child or vulnerable person",
    "Endangering life",
    "Intentional destruction of a viable unborn child",
    "Racially or religiously aggravated assault with injury",
    "Assault without injury",
    "Assault without injury on a constable",
    "Child abduction",
    "Conspiracy to murder",
    "Cruelty to children/young persons",
    "Kidnapping and false imprisonment",
    "Modern slavery",
    "Procuring illegal abortion",
    "Racially or religiously aggravated assault without injury",
    "Threats to kill"
]
__all__ = ["police_forces", "offence_types"]
